FROM rabbitmq:4.0-management

# Expose the necessary ports
EXPOSE 5672 15672

# Enable the RabbitMQ management plugin
RUN rabbitmq-plugins enable --offline rabbitmq_management

# Configure RabbitMQ to allow remote connections
COPY rabbitmq.conf /etc/rabbitmq/rabbitmq.conf

CMD ["sh", "/home/synthheadUser/receive_message.sh"]